name: Download YouTube Video

on:
  workflow_dispatch:
    inputs:
      youtube_url:
        description: "YouTube video URL"
        required: true
        type: string

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install yt-dlp
      - name: Install yt-dlp
        run: |
          python3 -m pip install --upgrade pip
          pip3 install yt-dlp

      # Download video
      - name: Download YouTube video
        run: |
          yt-dlp \
            --no-playlist \
            --js-runtimes node \
            -f "bv*[height<=720]+ba/b[height<=720]" \
            -o "video.%(ext)s" \
            "${{ inputs.youtube_url }}"

      # Upload artifact
      - name: Upload video
        uses: actions/upload-artifact@v4
        with:
          name: youtube-video
          path: video.*